//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalClinic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conclusion
    {
        public int Id { get; set; }
        public Nullable<int> MedCardId { get; set; }
        public int AppoinmentId { get; set; }
        public string Complaints { get; set; }
        public int AnamnesisId { get; set; }
        public int ExaminationId { get; set; }
        public string AdditionalInfo { get; set; }
        public string ConclusionResult { get; set; }
    
        public virtual Anamnesis Anamnesis { get; set; }
        public virtual Appointment Appointment { get; set; }
        public virtual Examination Examination { get; set; }
        public virtual MedCard MedCard { get; set; }
    }
}
